# Generated by Django 4.0.6 on 2024-06-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrevisaoTempo',
        ),
    ]
