# Generated by Django 4.0.6 on 2024-06-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0004_remove_previsao_icone_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoProximos5Dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao_tempo', models.CharField(max_length=100)),
                ('precipitacao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.cidade')),
            ],
        ),
    ]
