# Generated by Django 4.0.6 on 2024-05-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_course_disciplinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='disciplinas',
        ),
    ]
