# Generated by Django 4.0.6 on 2024-05-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_course_disciplines_discipline_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='teachers',
            field=models.ManyToManyField(related_name='disciplines', to='curso.teacher'),
        ),
    ]
