# Generated by Django 4.0.6 on 2024-05-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_discipline_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplines', to='curso.project'),
        ),
    ]
