# Generated by Django 4.0.6 on 2024-05-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_rename_titulo_musica_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='titulo',
            new_name='nome',
        ),
    ]
