# Generated by Django 4.0.6 on 2024-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
