# Generated by Django 4.0.6 on 2024-05-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_alter_autor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
